@host = http://127.0.0.1:6000/v1


### Login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "username": "emem",
  "password": "kandt123"
}


### Token verification
GET {{host}}/verify-token?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImVtZW0iLCJpZCI6MTAwLCJleHAiOjE2NTI5MzkxNjF9.BE-KrzczQrPR7Ba2_pHTakF7ae29IEXXeEXMDGqUq_o HTTP/1.1

